apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml -o output
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: compreface-postgres-db
  name: compreface-postgres-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: compreface-postgres-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml -o output
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/subcenter-arcface-r100-gpu-default: "true"
        io.kompose.service: compreface-postgres-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: frs
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: exadel/compreface-postgres-db:1.1.0
          name: compreface-postgres-db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: compreface-postgres-db
  namespace: default
spec:
  selector:
    io.kompose.service: compreface-postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432