apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml -o output
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: compreface-fe
  name: compreface-fe
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: compreface-fe
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml -o output
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/subcenter-arcface-r100-gpu-default: "true"
        io.kompose.service: compreface-fe
    spec:
      containers:
        - env:
            - name: CLIENT_MAX_BODY_SIZE
              value: 10M
            - name: PROXY_CONNECT_TIMEOUT
              value: 10000ms
            - name: PROXY_READ_TIMEOUT
              value: 60000ms
          image: exadel/compreface-fe:1.1.0
          name: compreface-ui
          ports:
            - containerPort: 80
              hostPort: 8000
              protocol: TCP
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: compreface-admin
  namespace: default
spec:
  selector:
    io.kompose.service: compreface-admin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
