version: '3.4'

volumes:
  postgres-data:

services:
  compreface-postgres-db:
    image: exadel/compreface-postgres-db:1.1.0
    restart: always
    container_name: "compreface-postgres-db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=frs
    volumes:
      - postgres-data:/var/lib/postgresql/data

  compreface-admin:
    image: exadel/compreface-admin:1.1.0
    restart: always
    container_name: "compreface-admin"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/frs
      - SPRING_PROFILES_ACTIVE=dev
      - ENABLE_EMAIL_SERVER=false
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_USERNAME=
      - EMAIL_FROM=
      - EMAIL_PASSWORD=
      - ADMIN_JAVA_OPTS=${compreface_admin_java_options}
      - MAX_FILE_SIZE=5MB
      - MAX_REQUEST_SIZE=10MB
    depends_on:
      - compreface-postgres-db
      - compreface-api

  compreface-api:
    image: exadel/compreface-api:1.1.0
    restart: always
    container_name: "compreface-api"
    depends_on:
      - compreface-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/frs
      - SPRING_PROFILES_ACTIVE=dev
      - API_JAVA_OPTS=${compreface_api_java_options}
      - SAVE_IMAGES_TO_DB=false
      - MAX_FILE_SIZE=5MB
      - MAX_REQUEST_SIZE=10MB
      - CONNECTION_TIMEOUT=10000
      - READ_TIMEOUT=60000

  compreface-fe:
    image: exadel/compreface-fe:1.1.0
    restart: always
    container_name: "compreface-ui"
    ports:
      - "8000:80"
    depends_on:
      - compreface-api
      - compreface-admin
    environment:
      - CLIENT_MAX_BODY_SIZE=10M
      - PROXY_READ_TIMEOUT=60000ms
      - PROXY_CONNECT_TIMEOUT=10000ms

  compreface-core:
    image: exadel/compreface-core:1.1.0-arcface-r100-gpu
    restart: always
    container_name: "compreface-core"
    # runtime: nvidia
    environment:
      - ML_PORT=3000
      - IMG_LENGTH_LIMIT=${max_detect_size}
      - UWSGI_PROCESSES=${uwsgi_processes:-2}
      - UWSGI_THREADS=${uwsgi_threads:-1}

