# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compreface-core
spec:
  replicas: 1 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: compreface-core
  template:
    metadata:
      labels:
        app: compreface-core
    spec:
      containers:
        - name: compreface-core
          image: {{ .Values.core.repository }}:{{ .Values.core.tag }}
          ports:
            - containerPort: 3000
          env:
            - name: ML_PORT
              value: "3000"
            - name: IMG_LENGTH_LIMIT
              value: "{{ .Values.max_detect_size }}"
            - name: UWSGI_PROCESSES
              value: "{{ .Values.uwsgi_processes | default "2" }}"
            - name: UWSGI_THREADS
              value: "{{ .Values.uwsgi_threads | default "1" }}"
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: compreface-core
spec:
  type: ClusterIP
  selector:
    app: core
  ports:
    - port: {{ .Values.core.port }}
