# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compreface-core
  labels:
    app: core
spec:
  replicas: 1  # You can set the desired number of replicas using .Values.core.replicas if needed
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - name: compreface-core
          image: {{ .Values.core.repository }}:{{ .Values.core.tag }}
          env:
            - name: ML_PORT
              value: "{{ .Values.core.port }}"
            - name: IMG_LENGTH_LIMIT
              value: "{{ .Values.maxDetectSize }}"
            - name: UWSGI_PROCESSES
              value: "{{ .Values.uwsgiProcesses | default "2" }}"
            - name: UWSGI_THREADS
              value: "{{ .Values.uwsgiThreads | default "1" }}"
          resources:
            limits:
              nvidia.com/gpu: {{ .Values.gpuCount }}
            requests:
              nvidia.com/gpu: {{ .Values.gpuCount }}

---
apiVersion: v1
kind: Service
metadata:
  name: compreface-core
spec:
  type: ClusterIP
  selector:
    app: core
  ports:
    - port: {{ .Values.core.port }}
