apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: core
  name: {{ .Values.core.name }}
spec:
  replicas: {{ .Values.core.replicas }}
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - name: {{ .Values.core.name }}
          env:
            - name: ML_PORT
              value: "{{ .Values.core.port }}"
          image: {{ .Values.core.repository }}:{{ .Values.core.tag }}
          ports:
            - containerPort: {{ .Values.core.port }}
          resources:  # Define GPU resources here
            limits:
              nvidia.com/gpu: 1
            requests:
              nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: compreface-core
spec:
  type: ClusterIP
  selector:
    app: core
  ports:
    - port: {{ .Values.core.port }}
